
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.3.0
 * Query Engine version: 9d6ad21cbbceab97458517b147a6a09ff43aa735
 */
Prisma.prismaVersion = {
  client: "7.3.0",
  engine: "9d6ad21cbbceab97458517b147a6a09ff43aa735"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  avatarUrl: 'avatarUrl',
  password: 'password',
  phone: 'phone',
  publicKey: 'publicKey',
  encryptedPrivateKey: 'encryptedPrivateKey',
  otpCode: 'otpCode',
  otpExpiry: 'otpExpiry',
  isVerified: 'isVerified',
  deviceId: 'deviceId',
  deviceInfo: 'deviceInfo',
  location: 'location',
  allowedCountry: 'allowedCountry',
  isBanned: 'isBanned',
  isFirstLogin: 'isFirstLogin',
  currentLocation: 'currentLocation',
  lastSeen: 'lastSeen',
  isOnline: 'isOnline',
  role: 'role',
  canPublishNotifications: 'canPublishNotifications',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserInvitationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  token: 'token',
  status: 'status',
  title: 'title',
  description: 'description',
  imageBase64: 'imageBase64',
  type: 'type',
  date: 'date',
  location: 'location',
  maxGuests: 'maxGuests',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvitationGuestScalarFieldEnum = {
  id: 'id',
  invitationId: 'invitationId',
  name: 'name',
  phone: 'phone',
  confirmedAt: 'confirmedAt'
};

exports.Prisma.FollowScalarFieldEnum = {
  id: 'id',
  followerId: 'followerId',
  followingId: 'followingId',
  createdAt: 'createdAt'
};

exports.Prisma.OrganizationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  logo: 'logo',
  address: 'address',
  isSuspended: 'isSuspended',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  ownerId: 'ownerId'
};

exports.Prisma.OrganizationCollaborationScalarFieldEnum = {
  id: 'id',
  orgAId: 'orgAId',
  orgBId: 'orgBId',
  status: 'status',
  createdBy: 'createdBy',
  invitedBy: 'invitedBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CollaborationGroupScalarFieldEnum = {
  id: 'id',
  collaborationId: 'collaborationId',
  name: 'name',
  publicKey: 'publicKey',
  headId: 'headId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CollaborationGroupMemberScalarFieldEnum = {
  id: 'id',
  groupId: 'groupId',
  userId: 'userId',
  orgId: 'orgId',
  encryptedDeptKey: 'encryptedDeptKey',
  createdAt: 'createdAt'
};

exports.Prisma.CollaborationTaskScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  status: 'status',
  priority: 'priority',
  startDate: 'startDate',
  dueDate: 'dueDate',
  completedAt: 'completedAt',
  groupId: 'groupId',
  creatorId: 'creatorId',
  assigneeId: 'assigneeId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CollaborationDocumentScalarFieldEnum = {
  id: 'id',
  groupId: 'groupId',
  filename: 'filename',
  type: 'type',
  data: 'data',
  uploadedBy: 'uploadedBy',
  createdAt: 'createdAt'
};

exports.Prisma.CollaborationNoteScalarFieldEnum = {
  id: 'id',
  groupId: 'groupId',
  title: 'title',
  content: 'content',
  textSize: 'textSize',
  order: 'order',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CollaborationEditorialItemScalarFieldEnum = {
  id: 'id',
  groupId: 'groupId',
  title: 'title',
  description: 'description',
  type: 'type',
  status: 'status',
  channel: 'channel',
  scheduledAt: 'scheduledAt',
  publishedAt: 'publishedAt',
  assigneeId: 'assigneeId',
  order: 'order',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DepartmentEditorialItemScalarFieldEnum = {
  id: 'id',
  deptId: 'deptId',
  title: 'title',
  description: 'description',
  type: 'type',
  status: 'status',
  channel: 'channel',
  scheduledAt: 'scheduledAt',
  publishedAt: 'publishedAt',
  assigneeId: 'assigneeId',
  order: 'order',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrganizationMemberScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  orgId: 'orgId',
  role: 'role',
  joinedAt: 'joinedAt'
};

exports.Prisma.DepartmentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  orgId: 'orgId',
  publicKey: 'publicKey',
  headId: 'headId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DepartmentNoteScalarFieldEnum = {
  id: 'id',
  deptId: 'deptId',
  title: 'title',
  content: 'content',
  textSize: 'textSize',
  order: 'order',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DepartmentDocumentScalarFieldEnum = {
  id: 'id',
  deptId: 'deptId',
  filename: 'filename',
  type: 'type',
  data: 'data',
  uploadedBy: 'uploadedBy',
  createdAt: 'createdAt'
};

exports.Prisma.DepartmentGoalScalarFieldEnum = {
  id: 'id',
  deptId: 'deptId',
  title: 'title',
  description: 'description',
  targetValue: 'targetValue',
  currentValue: 'currentValue',
  period: 'period',
  periodKey: 'periodKey',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DepartmentMeetingScalarFieldEnum = {
  id: 'id',
  deptId: 'deptId',
  title: 'title',
  description: 'description',
  agenda: 'agenda',
  meetingDate: 'meetingDate',
  location: 'location',
  createdBy: 'createdBy',
  minutes: 'minutes',
  minutesAt: 'minutesAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DepartmentPollScalarFieldEnum = {
  id: 'id',
  deptId: 'deptId',
  question: 'question',
  options: 'options',
  endDate: 'endDate',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PollVoteScalarFieldEnum = {
  id: 'id',
  pollId: 'pollId',
  userId: 'userId',
  optionIndex: 'optionIndex',
  createdAt: 'createdAt'
};

exports.Prisma.TeamDecisionScalarFieldEnum = {
  id: 'id',
  deptId: 'deptId',
  title: 'title',
  description: 'description',
  voteDeadline: 'voteDeadline',
  status: 'status',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DecisionVoteScalarFieldEnum = {
  id: 'id',
  decisionId: 'decisionId',
  userId: 'userId',
  vote: 'vote',
  createdAt: 'createdAt'
};

exports.Prisma.DepartmentMemberScalarFieldEnum = {
  id: 'id',
  deptId: 'deptId',
  userId: 'userId',
  encryptedDeptKey: 'encryptedDeptKey'
};

exports.Prisma.GroupScalarFieldEnum = {
  id: 'id',
  name: 'name',
  isDirect: 'isDirect',
  deptId: 'deptId',
  collaborationGroupId: 'collaborationGroupId',
  lockCodeHash: 'lockCodeHash',
  lockSetByUserId: 'lockSetByUserId',
  lockedAt: 'lockedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ConversationDeletionRequestScalarFieldEnum = {
  id: 'id',
  groupId: 'groupId',
  requestedBy: 'requestedBy',
  createdAt: 'createdAt'
};

exports.Prisma.GroupDocumentScalarFieldEnum = {
  id: 'id',
  groupId: 'groupId',
  title: 'title',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GroupNoteScalarFieldEnum = {
  id: 'id',
  documentId: 'documentId',
  title: 'title',
  content: 'content',
  textSize: 'textSize',
  order: 'order',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GroupNoteShareScalarFieldEnum = {
  id: 'id',
  noteId: 'noteId',
  sharedWithId: 'sharedWithId',
  canEdit: 'canEdit',
  createdAt: 'createdAt'
};

exports.Prisma.GroupMemberScalarFieldEnum = {
  id: 'id',
  groupId: 'groupId',
  userId: 'userId',
  joinedAt: 'joinedAt',
  lastReadAt: 'lastReadAt'
};

exports.Prisma.MessageScalarFieldEnum = {
  id: 'id',
  content: 'content',
  senderId: 'senderId',
  groupId: 'groupId',
  isEdited: 'isEdited',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AttachmentScalarFieldEnum = {
  id: 'id',
  messageId: 'messageId',
  type: 'type',
  filename: 'filename',
  data: 'data',
  createdAt: 'createdAt'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  content: 'content',
  userId: 'userId',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  isRead: 'isRead'
};

exports.Prisma.AnnouncementScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  publisherId: 'publisherId',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  isActive: 'isActive'
};

exports.Prisma.AnnouncementReadScalarFieldEnum = {
  id: 'id',
  announcementId: 'announcementId',
  userId: 'userId',
  readAt: 'readAt'
};

exports.Prisma.OrganizationRequestScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  cardCode: 'cardCode',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  reviewedBy: 'reviewedBy',
  reviewedAt: 'reviewedAt',
  orgId: 'orgId'
};

exports.Prisma.PendingSubscriptionPaymentScalarFieldEnum = {
  id: 'id',
  transactionId: 'transactionId',
  userId: 'userId',
  plan: 'plan',
  name: 'name',
  logo: 'logo',
  address: 'address',
  requestId: 'requestId',
  orgId: 'orgId',
  type: 'type',
  createdAt: 'createdAt'
};

exports.Prisma.PaymentOrderScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  plan: 'plan',
  name: 'name',
  logo: 'logo',
  address: 'address',
  requestId: 'requestId',
  orgId: 'orgId',
  type: 'type',
  amountFcfa: 'amountFcfa',
  status: 'status',
  approvedBy: 'approvedBy',
  approvedAt: 'approvedAt',
  rejectedAt: 'rejectedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentSettingScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value'
};

exports.Prisma.SubscriptionScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  plan: 'plan',
  startDate: 'startDate',
  endDate: 'endDate',
  maxDepartments: 'maxDepartments',
  maxMembersPerDept: 'maxMembersPerDept',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EventInvitationScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  title: 'title',
  description: 'description',
  eventType: 'eventType',
  eventDate: 'eventDate',
  maxAttendees: 'maxAttendees',
  imageUrl: 'imageUrl',
  token: 'token',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EventDepartmentBroadcastScalarFieldEnum = {
  id: 'id',
  eventId: 'eventId',
  deptId: 'deptId',
  createdAt: 'createdAt'
};

exports.Prisma.InvitationRSVPScalarFieldEnum = {
  id: 'id',
  eventId: 'eventId',
  name: 'name',
  phone: 'phone',
  createdAt: 'createdAt'
};

exports.Prisma.UserPageScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  handle: 'handle',
  bio: 'bio',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PostScalarFieldEnum = {
  id: 'id',
  pageId: 'pageId',
  type: 'type',
  content: 'content',
  imageUrl: 'imageUrl',
  caption: 'caption',
  reference: 'reference',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LikeScalarFieldEnum = {
  id: 'id',
  postId: 'postId',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.CommentScalarFieldEnum = {
  id: 'id',
  postId: 'postId',
  userId: 'userId',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  parentId: 'parentId'
};

exports.Prisma.PostReadScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  postId: 'postId',
  readAt: 'readAt'
};

exports.Prisma.TaskScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  status: 'status',
  priority: 'priority',
  startDate: 'startDate',
  dueDate: 'dueDate',
  completedAt: 'completedAt',
  deptId: 'deptId',
  creatorId: 'creatorId',
  assigneeId: 'assigneeId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TaskMessageScalarFieldEnum = {
  id: 'id',
  taskId: 'taskId',
  senderId: 'senderId',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TaskAttachmentScalarFieldEnum = {
  id: 'id',
  taskId: 'taskId',
  messageId: 'messageId',
  uploaderId: 'uploaderId',
  filename: 'filename',
  url: 'url',
  fileType: 'fileType',
  size: 'size',
  createdAt: 'createdAt'
};

exports.Prisma.DepartmentMonthlyReportScalarFieldEnum = {
  id: 'id',
  deptId: 'deptId',
  userId: 'userId',
  month: 'month',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PushSubscriptionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  endpoint: 'endpoint',
  p256dh: 'p256dh',
  auth: 'auth',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserProSubscriptionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  plan: 'plan',
  startDate: 'startDate',
  endDate: 'endDate',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserProSettingsScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  blurOldMessages: 'blurOldMessages',
  preventScreenshot: 'preventScreenshot',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserPersonalTaskScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  description: 'description',
  status: 'status',
  priority: 'priority',
  dueDate: 'dueDate',
  completedAt: 'completedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserFinancialGoalScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  year: 'year',
  targetItem: 'targetItem',
  targetAmount: 'targetAmount',
  targetDate: 'targetDate',
  label: 'label',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserFinancialProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  monthlySalary: 'monthlySalary',
  supplementaryIncome: 'supplementaryIncome',
  currency: 'currency',
  preferredSavingsRate: 'preferredSavingsRate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserMonthlyStatementScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  year: 'year',
  month: 'month',
  salaryReceived: 'salaryReceived',
  supplementaryIncome: 'supplementaryIncome',
  totalExpenses: 'totalExpenses',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserFinancialEntryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  year: 'year',
  month: 'month',
  type: 'type',
  amount: 'amount',
  note: 'note',
  isConfirmed: 'isConfirmed',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserMonthlyProgressScalarFieldEnum = {
  id: 'id',
  goalId: 'goalId',
  year: 'year',
  month: 'month',
  amount: 'amount',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.UserRole = exports.$Enums.UserRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN'
};

exports.InvitationStatus = exports.$Enums.InvitationStatus = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED'
};

exports.InvitationType = exports.$Enums.InvitationType = {
  WEDDING: 'WEDDING',
  DINNER: 'DINNER',
  BIRTHDAY: 'BIRTHDAY',
  PARTY: 'PARTY',
  OTHER: 'OTHER'
};

exports.CollaborationStatus = exports.$Enums.CollaborationStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  REJECTED: 'REJECTED'
};

exports.TaskStatus = exports.$Enums.TaskStatus = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

exports.TaskPriority = exports.$Enums.TaskPriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

exports.FileType = exports.$Enums.FileType = {
  IMAGE: 'IMAGE',
  PDF: 'PDF',
  WORD: 'WORD',
  AUDIO: 'AUDIO',
  OTHER: 'OTHER'
};

exports.NoteTextSize = exports.$Enums.NoteTextSize = {
  SMALL: 'SMALL',
  NORMAL: 'NORMAL',
  LARGE: 'LARGE'
};

exports.EditorialItemType = exports.$Enums.EditorialItemType = {
  ARTICLE: 'ARTICLE',
  POST: 'POST',
  VIDEO: 'VIDEO',
  STORY: 'STORY',
  PODCAST: 'PODCAST',
  NEWSLETTER: 'NEWSLETTER',
  OTHER: 'OTHER'
};

exports.EditorialStatus = exports.$Enums.EditorialStatus = {
  DRAFT: 'DRAFT',
  IN_PROGRESS: 'IN_PROGRESS',
  REVIEW: 'REVIEW',
  PUBLISHED: 'PUBLISHED'
};

exports.OrgRole = exports.$Enums.OrgRole = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER'
};

exports.DecisionVoteType = exports.$Enums.DecisionVoteType = {
  FOR: 'FOR',
  AGAINST: 'AGAINST',
  ABSTAIN: 'ABSTAIN'
};

exports.RequestStatus = exports.$Enums.RequestStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED'
};

exports.PaymentOrderStatus = exports.$Enums.PaymentOrderStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

exports.SubscriptionPlan = exports.$Enums.SubscriptionPlan = {
  FREE: 'FREE',
  BASIC: 'BASIC',
  PROFESSIONAL: 'PROFESSIONAL',
  ENTERPRISE: 'ENTERPRISE'
};

exports.EventType = exports.$Enums.EventType = {
  PROFESSIONAL: 'PROFESSIONAL',
  DINNER: 'DINNER',
  MEETING: 'MEETING',
  PARTY: 'PARTY',
  CONFERENCE: 'CONFERENCE',
  WORKSHOP: 'WORKSHOP',
  OTHER: 'OTHER'
};

exports.PostType = exports.$Enums.PostType = {
  TWEET: 'TWEET',
  CONTENT: 'CONTENT'
};

exports.UserProPlan = exports.$Enums.UserProPlan = {
  MONTHLY: 'MONTHLY',
  SIX_MONTHS: 'SIX_MONTHS',
  TWELVE_MONTHS: 'TWELVE_MONTHS'
};

exports.PersonalTaskStatus = exports.$Enums.PersonalTaskStatus = {
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
  CANCELLED: 'CANCELLED'
};

exports.PersonalTaskPriority = exports.$Enums.PersonalTaskPriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

exports.FinancialGoalType = exports.$Enums.FinancialGoalType = {
  ANNUAL_SAVINGS: 'ANNUAL_SAVINGS',
  MATERIAL_PURCHASE: 'MATERIAL_PURCHASE'
};

exports.FinancialEntryType = exports.$Enums.FinancialEntryType = {
  SALARY: 'SALARY',
  SUPPLEMENTARY_INCOME: 'SUPPLEMENTARY_INCOME',
  EXPENSE: 'EXPENSE'
};

exports.Prisma.ModelName = {
  User: 'User',
  UserInvitation: 'UserInvitation',
  InvitationGuest: 'InvitationGuest',
  Follow: 'Follow',
  Organization: 'Organization',
  OrganizationCollaboration: 'OrganizationCollaboration',
  CollaborationGroup: 'CollaborationGroup',
  CollaborationGroupMember: 'CollaborationGroupMember',
  CollaborationTask: 'CollaborationTask',
  CollaborationDocument: 'CollaborationDocument',
  CollaborationNote: 'CollaborationNote',
  CollaborationEditorialItem: 'CollaborationEditorialItem',
  DepartmentEditorialItem: 'DepartmentEditorialItem',
  OrganizationMember: 'OrganizationMember',
  Department: 'Department',
  DepartmentNote: 'DepartmentNote',
  DepartmentDocument: 'DepartmentDocument',
  DepartmentGoal: 'DepartmentGoal',
  DepartmentMeeting: 'DepartmentMeeting',
  DepartmentPoll: 'DepartmentPoll',
  PollVote: 'PollVote',
  TeamDecision: 'TeamDecision',
  DecisionVote: 'DecisionVote',
  DepartmentMember: 'DepartmentMember',
  Group: 'Group',
  ConversationDeletionRequest: 'ConversationDeletionRequest',
  GroupDocument: 'GroupDocument',
  GroupNote: 'GroupNote',
  GroupNoteShare: 'GroupNoteShare',
  GroupMember: 'GroupMember',
  Message: 'Message',
  Attachment: 'Attachment',
  Notification: 'Notification',
  Announcement: 'Announcement',
  AnnouncementRead: 'AnnouncementRead',
  OrganizationRequest: 'OrganizationRequest',
  PendingSubscriptionPayment: 'PendingSubscriptionPayment',
  PaymentOrder: 'PaymentOrder',
  PaymentSetting: 'PaymentSetting',
  Subscription: 'Subscription',
  EventInvitation: 'EventInvitation',
  EventDepartmentBroadcast: 'EventDepartmentBroadcast',
  InvitationRSVP: 'InvitationRSVP',
  UserPage: 'UserPage',
  Post: 'Post',
  Like: 'Like',
  Comment: 'Comment',
  PostRead: 'PostRead',
  Task: 'Task',
  TaskMessage: 'TaskMessage',
  TaskAttachment: 'TaskAttachment',
  DepartmentMonthlyReport: 'DepartmentMonthlyReport',
  PushSubscription: 'PushSubscription',
  UserProSubscription: 'UserProSubscription',
  UserProSettings: 'UserProSettings',
  UserPersonalTask: 'UserPersonalTask',
  UserFinancialGoal: 'UserFinancialGoal',
  UserFinancialProfile: 'UserFinancialProfile',
  UserMonthlyStatement: 'UserMonthlyStatement',
  UserFinancialEntry: 'UserFinancialEntry',
  UserMonthlyProgress: 'UserMonthlyProgress'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
